### PR TITLE
add swagger decoraters

### PR DESCRIPTION
**Pull request by ghost**
Create a login API in which user login with correct email and password and an OTP is send to verify the user and in return access and refresh token is given.

### CODE REVIEW

**Review by shyamsharma-kiwi — CHANGES_REQUESTED** [review]
why we are keeping username and password in code?
              auth_user="mohd.asad@kiwitech.com", auth_password="3339khanasad")

Can we not call this from .env file?

**Review by shyamsharma-kiwi — CHANGES_REQUESTED** [review]
have we not created constant file for error or success msg?
      raise serializers.ValidationError('Invalid OTP')

**Review by shyamsharma-kiwi — CHANGES_REQUESTED** [review]
all msg and magic number should be call from constant file.

**Comment by ghost** [comment]
created constant.py file and messages.py file.
secret data saved in .env file.

**Review by shyamsharma-kiwi — APPROVED** [review]
move email and password in .env file

**Pull request merged**
